# Generated by Django 5.0.4 on 2024-04-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='coord_id',
            new_name='coord',
        ),
        migrations.RenameField(
            model_name='pass',
            old_name='levels',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='fisrt_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='otc',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
