# Generated by Django 5.0.4 on 2024-04-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pass',
            old_name='user',
            new_name='tourist',
        ),
    ]
