# Generated by Django 5.0.4 on 2024-04-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_rename_user_pass_tourist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='rel_pass',
        ),
        migrations.AddField(
            model_name='pass',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.images'),
        ),
    ]
