# Generated by Django 5.0.4 on 2024-04-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_remove_images_rel_pass_pass_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='rel_pass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.pass'),
            preserve_default=False,
        ),
    ]
