# Generated by Django 5.0.4 on 2024-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_rename_fisrt_name_users_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='level',
        ),
        migrations.AddField(
            model_name='pass',
            name='lvl_autumn',
            field=models.CharField(choices=[('n/d', 'н/у'), ('n/c', 'н/к'), ('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], default='n/d', max_length=3),
        ),
        migrations.AddField(
            model_name='pass',
            name='lvl_spring',
            field=models.CharField(choices=[('n/d', 'н/у'), ('n/c', 'н/к'), ('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], default='n/d', max_length=3),
        ),
        migrations.AddField(
            model_name='pass',
            name='lvl_summer',
            field=models.CharField(choices=[('n/d', 'н/у'), ('n/c', 'н/к'), ('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], default='n/d', max_length=3),
        ),
        migrations.AddField(
            model_name='pass',
            name='lvl_winter',
            field=models.CharField(choices=[('n/d', 'н/у'), ('n/c', 'н/к'), ('1A', '1А'), ('1B', '1Б'), ('2A', '2А'), ('2B', '2Б'), ('3A', '3А'), ('3B', '3Б')], default='n/d', max_length=3),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
